### ISSUE TITLE
Breaking Changes: Update all code to Aspire.Hosting.AppHost Version 8.2.0

### ISSUE THREAD

**Issue by ericbrunner** [PacktPublishing/Pragmatic-Microservices-with-CSharp-and-Azure#211]
According to breaking changes there is a need to update all `*AppHost.csproj` to
`Aspire.Hosting.AppHost` nuget packs to `8.2.0` otherwise you get a compiler error.

ref: [https://devblogs.microsoft.com/dotnet/announcing-dotnet-aspire-8-2/#breaking-changes3](https://devblogs.microsoft.com/dotnet/announcing-dotnet-aspire-8-2/#breaking-changes3)

**Comment by christiannagel** [comment]
Hi Eric,

yes, thanks! This happens when the 8.2 workload is installed. I'll update all the samples!

Greetings,
Christian


________________________________
From: Eric Brunner ***@***.***>
Sent: Wednesday, September 4, 2024 11:27 PM
To: PacktPublishing/Pragmatic-Microservices-with-CSharp-and-Azure ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PacktPublishing/Pragmatic-Microservices-with-CSharp-and-Azure] Breaking Changes: Update all code to Aspire.Hosting.AppHost Version 8.2.0 (Issue #211)


According to breaking changes there is a need to update all *AppHost.csproj to
Aspire.Hosting.AppHost nuget packs to 8.2.0 otherwise you get a compiler error.

ref: https://devblogs.microsoft.com/dotnet/announcing-dotnet-aspire-8-2/#breaking-changes3
